# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://yupi.icu">编程导航知识星球</a>
server:
  port: 8101
  address: 0.0.0.0
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
      timeout: 2592000
      store-type: redis
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.250.175:3306/interviewer_db
    username: xiaoMeng
    password: zn3x2bZFmhdJ8Pi2
  session:
    # 30 天过期
    timeout: 2592000
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    timeout: 2592000
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: 123456
file:
  upload:
    path: /www/wwwroot/Dream_Interviewer/uploadfile/
